### ISSUE TITLE
widgets default slide

### ISSUE THREAD

**Issue by jabdoa2** [missionpinball/mpf-mc#117]
When i provide a slide to a widget_player and the slide is not active, the widget is shown on the current active slide on the default target

**Comment by toomanybrians** [comment]
@jabdoa2, When you say a slide is not active, do you mean a slide that's created and not the current one, or a slide that has not been created yet? If it's the first thing, I am not able to reproduce this, and if it's the second, then I think the fix for #118 will address this use case too?

Or if I'm totally wrong on this, give me an example of what you mean. I'm going to add you as an assignee to this so you see it, then pass it back to me and I'll implement it.

**Comment by toomanybrians** [comment]
added tests to verify this is all working as it should be
