### ISSUE TITLE
Using same event as the one that starts a mode will not execute

### ISSUE THREAD

**Issue by cfbenn** [missionpinball/mpf-mc#231]
When using the same event in "start_events" of a mode and a widget_player, the widget_player is never executed.  If event is different for widget_player it will work.  This also appears to be true for other event triggers like slide_players but is not tested.

Look at base.yaml for an example that works and another example that does not work.

[Mode Start Event Cannot Be Used Elsewhere.zip.txt](https://github.com/missionpinball/mpf-mc/files/709984/Mode.Start.Event.Cannot.Be.Used.Elsewhere.zip.txt)

**Comment by toomanybrians** [comment]
This is a known behavior since the config players don't register their event handlers until the mode starts, so if you use the same event that starts a mode as a config player then it will never fire since by the time it registered the handler, the event has already happened.

But I'll keep this open because maybe this is a special case we should look for to create an error? It would be pretty easy to just make sure that no config player event names are in the mode's start events and then raise an error if they are. Thoughts?
