### ISSUE TITLE
Higher priority slide not showing

### ISSUE THREAD

**Issue by cfbenn** [missionpinball/mpf-mc#237]
When a slide is displayed with a higher priority and no parameters in slide_player, it is not shown.

Attached is sample code and details.

[MPFBug_SlideNotShowing.zip.txt](https://github.com/missionpinball/mpf-mc/files/732450/MPFBug_SlideNotShowing.zip.txt)

**Comment by toomanybrians** [comment]
Several issues in the attached config. None are bugs.

1. The priority of a slide in the slide player is added to the base priority of the mode. Your base mode is p200 and the slide player entry in it is p200, so that slide shows at 400, but the bug base mode is 350 with no priority for the slide, so the base slide will show on top of it.

2. background_color: is spelled wrong

3. Default color of text is white, so white text on white bg will not show.

4. When you enter a slide name with no settings in the slide player, you entered it with an empty list which overwrites the named slide's setting. (See the docs for the proper way to overwrite it.)

So this is wrong:

```
slide_player:
  mode_droptargetbankx_started:
     BugBase_Debug_ResetDrops: []
```

This is the right way to do an express config.

```
slide_player:
  mode_droptargetbankx_started: BugBase_Debug_ResetDrops
```
