### ISSUE TITLE
Update tests to work with non writable permissions

### ISSUE THREAD

**Issue by GabeKnuth** [missionpinball/mpf-mc#36]
Tests on Ubuntu 14.04 are failing with permissions errors on __mpfcache__ and high_scores.yaml because it can't write to files/folders in /usr/local/lib...

MPF Unit Tests:
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.4/dist-packages/mpf/tests/machine_files/null/__mpfcache__'
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.4/dist-packages/mpf/tests/machine_files/high_score/data/high_scores.yaml

From MC Tests:
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.4/dist-packages/mpfmc/tests/machine_files/mpf_plugin_config_player_validation/__mpfcache__'

This should be fixed for .30 because we tell people to run the unittests to see if their install works.

**Comment by toomanybrians** [comment]
The __mpfcache__ thing will fail even when running MPF (not just tests) if the user doesn't have write access to the machine folder. I guess that's not likely, but we can change it so that it writes it in a try: block and ignores the error if it can't write it.

For high_scores.yaml, we can just mock the actual write to disk during the tests because we don't need it.

**Comment by jabdoa2** [comment]
Maybe we can just dump those files to a temp folder? In a deployment scenario you would typically have your machine folder read only because it would be on a read only partition. Temp should be fine because we don't case if we loose those files.

A similar problems applies to data and logs: In a deployment scenario they would have to live somewhere different (on linux in /var/log/xxx).

**Comment by toomanybrians** [comment]
this is done for the high_scores.yaml.

@jabdoa2, can you do the temp folder thing for 0.30? We need it on linux.

**Comment by jabdoa2** [comment]
Resolved in: https://github.com/missionpinball/mpf/pull/242
