### ISSUE TITLE
WidgetPlayer seems to ignore events from RandomEventPlayer

### ISSUE THREAD

**Issue by kaydeeH** [missionpinball/mpf-mc#369]
I haven't fully investigated the scope so this may be a bigger issue, but we have at least pinned this down. We have a random event player that throws an event, say "event_x". Widget player is configured to listen for "event_x" and add a given text widget to an existing slide. According to the log, "event_x" is thrown but the widget is never added, no errors reported. If we add a section to EventPlayer to listen for "event_x", then throw "event_x_not_random", then change the widget player to listen instead for "event_x_not_random" (no other changes), the widget is added to the slide as we would expect.

MPF: 0.51.3
MC: 0.51.4

**Comment by kaydeeH** [comment]
For what it's worth, ShowPlayer does seem to listen to the random events just fine, so this seems to be something isolated to either the McConfigPlayer or WidgetPlayer classes.

**Comment by kaydeeH** [comment]
One other detail, we've only tested this with random events of scope "machine", not "player", though I'm not sure if that matters.

**Comment by kaydeeH** [comment]
Also, the mc log doesn't show the random events. It only shows standard events. The random events only show up in the mpf log.

**Comment by avanwinkle** [comment]
Hey Kaydee, thanks for the issue filing. 

I've noticed in the past that MC can be particular when it comes to events that it listens to. Basically, most events start in MPF and are posted there, and MC has a list of events that it also wants to know about. MC tells MPF "hey these are the events I care about" and when MPF posts one of those events, it'll share it with MC. If MC didn't tell MPF that it cares about a particular event, MPF won't share it.

That may explain why the random events are showing up in the mpf log (because mpf is triggering them) and not the mc log (because mc didn't ask for them).

Where it can get tricky/complicated is when the events have conditions or template names, because MC doesn't always know what to ask for and MPF doesn't always know when an event qualifies. I've encountered this a few times, something like MC was waiting for `this_event_name` and MPF had `this_event_name{some_condition==true}`. Even though the event that was broadcast was "this_event_name", the connection didn't match.

Good news: MPF 0.52 has restructured events that eliminate much of the MPF-MC disconnect, so this may not be an issue for long. In the meantime, do you have a snippet of the code you could share? I'd be happy to take a look to try and repro the issue you're seeing.

**Comment by jabdoa2** [comment]
should be fixed in 0.52+
