### ISSUE TITLE
Exception when running the audio tests

### ISSUE THREAD

**Issue by jabdoa2** [missionpinball/mpf-mc#42]
```
Exception ignored in: 'Pinball.mpf_mc.mpfmc.core.audio.audio_interface.Track._play_sound_on_sound_player'
OverflowError: value too large to convert to int
Exception ignored in: 'Pinball.mpf_mc.mpfmc.core.audio.audio_interface.Track._play_sound_on_sound_player'
OverflowError: value too large to convert to int 
```

On one of my Lubuntu 14.04 machines. Sound does not play. Works on my other Lubuntu 14.04 machine.

**Comment by qcapen** [comment]
Perhaps int is only 16-bits on the problem platform and a 32 bit value is needed?  I have gone through the various data structures in the audio library and made sure and sample position related variable uses long instead of int.  Hopefully this change will resolve the issue.

Any suggestions on how to write a test for this one?

**Comment by qcapen** [comment]
This was a bit-depth problem for a particular data structure in the Cython code.  The problem was sound assets have a unique id that is accessed via the built-in Python id() function.  This returns a Python object that is a PyLong.  It was getting stored in the Cython code in an int C variable which works on some platforms, however int is too short on other platforms.  Changing the int to a long fixed the issue.

**Comment by qcapen** [comment]
Fixed
